package org.chat.model.database;
// Generated 10-nov-2016 15.53.56 by Hibernate Tools 4.3.1

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

    private Integer idMessage;
    private User userByIdTo;
    private User userByIdFrom;
    private String textMessage;
    private Boolean fromVisibility;
    private Boolean toVisibility;
    private Date timeMessage;
    private SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");

    public Message() {
    }

    public Message(User userByIdTo, User userByIdFrom, String textMessage) {
        this.userByIdTo = userByIdTo;
        this.userByIdFrom = userByIdFrom;
        this.textMessage = textMessage;
        this.timeMessage = new Date();
        this.toVisibility = true;
        this.fromVisibility = true;
    }


    public Integer getIdMessage() {
        return this.idMessage;
    }

    public void setIdMessage(Integer idMessage) {
        this.idMessage = idMessage;
    }

    public User getUserByIdTo() {
        return this.userByIdTo;
    }

    public void setUserByIdTo(User userByIdTo) {
        this.userByIdTo = userByIdTo;
    }

    public User getUserByIdFrom() {
        return this.userByIdFrom;
    }

    public void setUserByIdFrom(User userByIdFrom) {
        this.userByIdFrom = userByIdFrom;
    }

    public String getTextMessage() {
        return this.textMessage;
    }

    public void setTextMessage(String textMessage) {
        this.textMessage = textMessage;
    }

    public Boolean getFromVisibility() {
        return this.fromVisibility;
    }

    public void setFromVisibility(Boolean fromVisibility) {
        this.fromVisibility = fromVisibility;
    }

    public Boolean getToVisibility() {
        return this.toVisibility;
    }

    public void setToVisibility(Boolean toVisibility) {
        this.toVisibility = toVisibility;
    }

    public Date getTimeMessage() {
        return this.timeMessage;
    }
    
    public String getTime(){
        return sdf.format(timeMessage);
    }

    public void setTimeMessage(Date timeMessage) {
        this.timeMessage = timeMessage;
    }

    @Override
    public String toString() {
        return "Message{" + "idMessage=" + idMessage + ", userByIdTo=" + userByIdTo.getUsername() + ", userByIdFrom=" + userByIdFrom.getUsername() + ", textMessage=" + textMessage 
                + ", fromVisibility=" + fromVisibility + ", toVisibility=" + toVisibility + ", timeMessage=" + sdf.format(timeMessage)  + '}' + "\t\t";
    }

}
